language: node_js
node_js:
- 10.15.3
cache: npm
notifications:
  slack:
    secure: liZitL3fN2KBuXgpB7IGTSrkJOMVtRmCsFMusGEB5vS35mzdQyiCLzNN5gQTG+vBG7cXzVmS6m62QQ+k/zjvuf35jaGFfC8gvIL4amcbb4PnacXJoy1TMPSOAdV5TDBtd/db9csAsJ3ZxmRW6tTnPs8EtrpUEOlAz/w/CDjAfyew495XHSmk60j5NCQtJ9nukJKnrxeGau/6r0rkQTbNt18fyOslTsjFDzWt6nEmUT+DUx955py8lRxMTwsFHkuu1LQ6WzwNlBW/zQx8JToz3z8t2CO/TIYbSM4J29CpURS4rr+adhISF+Xvvxt/M4XaidjGgn+3CbD3yWED9DdLkXqAEwsvQM0JFlTPtbyxMHhQmK4+5DaE5BRJRnOqXnVGpTqlVEmkjJzfkpS5zH89TnPLvvr//OYbvcw0jiQhf7bzPo8B1s9wjEDVmYUalvMqVX8U/A4RTSddjIGSj31K1p/GqMmcJ01uDPT1WJrmnW2MSBNU2zmIEoT/JNV+iRsvG4BW9ijxpd0q632Rbg0Zp6NSznfaYMGGeaBw07Vy85s7em91oOtPURu9gyNPC2BOfTtg8jV31dK6e1Odh171btjHw/6LOgcj4OFU6de49fD0z1EhuTmQf6NmzT9BrRIScdXf994zVlk3jLeYsXDfXLaHBMh30BZiaofDrUTOonk=
