version: '3'

services:
  mongo:
    image: mongo:3.6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - messaging-mediator-network
  
  hearth:
    image: jembi/hearth:latest
    container_name: hearth
    depends_on:
      - mongo
    networks:
      - messaging-mediator-network
    environment:
      - server__fhirVersion=stu3
      - server__port=3447
      - authentication__type=disabled
      - mongodb__url=mongodb://mongo:27017/hearth
      - NODE_ENV=development
    ports:
      - "3447:3447"
  
  messaging-mediator:
    build: .
    container_name: messaging-mediator
    command: npm start
    networks:
      - messaging-mediator-network
    ports:
      - "3000:3000"
    environment:
        - NODE_ENV=development
        - HEARTH_HOST=hearth
        - HEARTH_PORT=3447
        - HEARTH_SCURED=false
        - PORT=3000
    volumes:
      - .:/code/
  
  rapidpro:
    image: sdehaan/rapidpro:v4
    container_name: rapidpro
    depends_on:
      - redis
      - postgresql
    ports:
      - '8000:8000'
    environment:
      - DOMAIN_NAME=localhost
      - ALLOWED_HOSTS=localhost
      - TEMBA_HOST=localhost
      - DJANGO_DEBUG=off
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=super-secret-key
      - MANAGEPY_COLLECTSTATIC=on
      - MANAGEPY_COMPRESS=on
      - MANAGEPY_INIT_DB=on
      - MANAGEPY_MIGRATE=on
    networks:
      - messaging-mediator-network
  
  celery_base:
    image: sdehaan/rapidpro:v4
    container_name: celery_base
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=super-secret-key
    command: ["/venv/bin/celery", "--beat", "--app=temba", "worker", "--loglevel=INFO", "--queues=celery,flows"]
    networks:
      - messaging-mediator-network
  
  celery_msgs:
    image: sdehaan/rapidpro:v4
    container_name: celery_msgs
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=super-secret-key
    command: ["/venv/bin/celery", "--app=temba", "worker", "--loglevel=INFO", "--queues=msgs,handler"]
    networks:
      - messaging-mediator-network
  
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - messaging-mediator-network
  
  postgresql:
    image: mdillon/postgis:9.6
    container_name: rapidpro_postgres
    environment:
      - POSTGRES_DB=rapidpro
    networks:
      - messaging-mediator-network

  courier:
    image: praekeltfoundation/courier
    container_name: courier
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
    environment:
      - COURIER_DOMAIN=localhost
      - COURIER_SPOOL_DIR=/tmp/courier/
      - COURIER_DB=postgres://postgres:postgres@postgresql/rapidpro
      - COURIER_REDIS=redis://redis:6379/8
    networks:
      - messaging-mediator-network
  

networks:
  messaging-mediator-network:
