version: '3'

services:
  mongo:
    image: mongo:3.6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - messaging-mediator-network
  
  hearth:
    image: jembi/hearth:latest
    container_name: hearth
    depends_on:
      - mongo
    networks:
      - messaging-mediator-network
    environment:
      - server__fhirVersion=stu3
      - server__port=3447
      - authentication__type=disabled
      - mongodb__url=mongodb://mongo:27017/hearth
      - NODE_ENV=development
    ports:
      - "3447:3447"
  
  openhim-core:
    image: jembi/openhim-core:5
    container_name: openhim-core
    depends_on:
      - mongo
    networks:
      - messaging-mediator-network
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - "./infrastructure/openhim-config.json/:/usr/src/app/config/development.json"
  
  openhim-console:
    image: jembi/openhim-console
    container_name: openhim-console
    networks:
      - messaging-mediator-network
    ports:
      - "9090:80"
  
  messaging-mediator:
    build: .
    container_name: messaging-mediator
    command: npm start
    networks:
      - messaging-mediator-network
    ports:
      - "3002:3002"
    environment:
        - NODE_ENV=development
        - HEARTH_HOST=hearth
        - HEARTH_PORT=3447
        - HEARTH_SCURED=false
        - PORT=3002
    volumes:
      - .:/code/

networks:
  messaging-mediator-network:
